FROM node:20-slim AS build

RUN mkdir -p /build
COPY src /build/src
COPY types /build/types
COPY package.json /build/
COPY package-lock.json /build/
COPY tsconfig.json /build/
WORKDIR /build

RUN npm ci --ignore-scripts
RUN npm run build

FROM node:20-slim
WORKDIR /app
COPY --from=build /build/dist /app/dist
COPY --from=build /build/node_modules /app/node_modules
COPY --from=build /build/package.json /app/package.json
USER 998

ENTRYPOINT ["node", "dist/mcp/server.js"]
